---
title: "Playlists nazareno"
output: html_notebook
---

```{r}
library(tidyverse)
library(viridis)
library(here)
theme_set(theme_minimal())
```


```{r}
file = read_csv("../data/playlists_nazareno.csv")
```

Quais as 10 playlists mais ouvidas? 
```{r}

 top_ten_playlists <-file %>% 
        group_by(playlist_name) %>% 
        summarise(times = n()) %>% 
        top_n(10) %>%
        ungroup() %>%
        arrange(-times) %>% 
    ggplot(aes(x=playlist_name, y = times)) + 
    geom_bar(stat = "identity") + 
    coord_flip() + 
    xlab("Nome da playlist") + 
    ylab("Número de registros")

top_ten_playlists
```

Quais as músicas mais ouvidas considerando apenas as faixas nomeadas? 
```{r}
top_hits <-file %>% 
        group_by(track_name) %>% 
        na.omit() %>%
        summarise(times = n()) %>% 
        top_n(10) %>% 
    ggplot(aes(x=track_name, y = times)) + 
    geom_count() + 
    coord_flip() + 
    xlab("Nome da faixa") + 
    ylab("Número de registros")

top_hits
```


```{r}
1- Quais as 10 playlists mais ouvidas?

2- Quais as músicas mais ouvidas considerando apenas as faixas nomeadas?

3- Quais album Nazareno Andrade ouve com mais frequência?

4- Que músicas, entre as faixas nomeadas, são mais "dançáveis"?

5- Que tipo de música Nazareno Andrade costuma ouvir? 

6- O que é possível identificar a partir dessas evidências (na questão 5)?

7- As faixas longas/curtas diferenciam-se (entre si ou em conjunto)?

8- A popularidade das músicas influencia no seu estilo? 

9- Quais seus artistas preferidos? 

10- É possivel identificar algum padrão instrumental nas músicas mais tocadas?
```

